services:
  max-bot:
    build: .
    ports:
      - "8001:8001"
    environment:
      - MAX_BOT_TOKEN
      - ADMIN_CHAT_ID
      - DEEPSEEK_API_KEY
      - YKASSA_SHOP_ID
      - YKASSA_SECRET_KEY
      - YKASSA_TEST_MODE
      - ADMIN_CHANNEL_ID
      - PORT=8001
      - SITE_API_URL=https://realplanninig-oss-salesplan-web-7eb2.twc1.net
    command: python main.py
    restart: always
