services:
  max-bot:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MAX_BOT_TOKEN
      - ADMIN_CHAT_ID
      - DEEPSEEK_API_KEY
      - YKASSA_SHOP_ID
      - YKASSA_SECRET_KEY
      - YKASSA_TEST_MODE
      - PORT
    restart: always
